import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ToastContainer from "./Toaster/toastContainer";
import ReduxContainer from "./_redux/ReduxContainer";

const roboto = Roboto({
  weight: ["100", "300", "400"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ToastContainer>{children}</ToastContainer>
      </body>
    </html>
  );
}
